### ISSUE TITLE
Clarify expected behaviour with identically named plates in separate experiments in the same config file

### ISSUE THREAD

**Issue by Swarchal** [Swarchal/cptools2#21]
If we add two experiments that share plate names, I'm not currently sure what happens.

There are at least 2 issues that will happen with this:
1. LoadData csv files with identical names will overwrite each other, or they are possibly overwritten as dictionary keys in the plateStore implementation.
2. Trying to remove plates without specifying which experiment is ambiguous.

We need to define the behaviour, or at least raise a warning/error if this happens.

```yaml
# experiment with plates named plate_A01, plate_A02... etc
experiment: /path/to/experiment_A

add plate:
    - experiment: /path/to/experiment_B
    - plates:
        - plate_A01
        - plate_A02
        - plate_A03

remove plate:
    - plates:
        - plate_A01
```

Options:
1. Detect if this happens and error, experiments should not share a config file if they have identically named plates.
2. Name LoadData csv files including the experiment name so they are not overwritten. In addition, `remove plate` in config needs to specify an experiment in addition to plate names.
